"""i

Revision ID: 72616a464131
Revises: 
Create Date: 2023-06-17 08:43:26.263428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72616a464131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('article_url')

    # ### end Alembic commands ###
